export const GET_COUNTRIES = "GET_COUNTRIES";

export const SEARCH_COUNTRIES = "SEARCH_COUNTRIES";

export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

export const RESET_COUNTRIES = "RESET_COUNTRIES";

export const FILTER_COUNTRIES_BY_CONTINENT = "FILTER_COUNTRIES_BY_CONTINENT";

export const FILTER_COUNTRIES_BY_ACTIVITY = "FILTER_COUNTRIES_BY_ACTIVITY";

export const SORT_COUNTRIES_BY_NAME_ASCENDING = "SORT_COUNTRIES_BY_NAME_ASCENDING";

export const SORT_COUNTRIES_BY_NAME_DESCENDING = "SORT_COUNTRIES_BY_NAME_DESCENDING";

export const SORT_COUNTRIES_BY_POPULATION_ASCENDING = "SORT_COUNTRIES_BY_POPULATION_ASCENDING";

export const SORT_COUNTRIES_BY_POPULATION_DESCENDING = "SORT_COUNTRIES_BY_POPULATION_DESCENDING";